#!/bin/bash

# parameters
dim="1 1 1"
sn=5
Tmax=1500

# functions
check_file() {
	local file=$1
	if [ ! -f "$file" ]; then
		echo "Error! $file is not exist!"
		echo "You should prepare POSCAR, INCAR, POTCAR, KPOINTS and thermal.conf to run this script"
		exit 1
	fi
}

check_program() {
	local program=$1
	if ! command -v "$program" &> /dev/null; then
		echo "Error! $program not found!"
		exit 1
	fi
}
make_dir() {
	local dir=$1
	if [ ! -d "$1" ]; then
		mkdir "$1"
	fi
}
call_line() {
	echo ">>>DFPT-QHA-phonopy-------------------------------------"
}

get_atomnum() {
	atomnum=0
	j=1
	sed -i "s/\r//" POSCAR
	ele=$(head -6 POSCAR|tail -1|tr -s [:space:]|sed 's/^[ ]*//g'|cut -d ' ' -f $j)
	elen=$(head -7 POSCAR|tail -1|tr -s [:space:]|sed 's/^[ ]*//g'|cut -d ' ' -f $j)
	while [ -n "$ele" ];do
		atomnum=$( expr $atomnum + $elen)
		j=$[j+1]
		ele_old=$ele
		ele=$(head -6 POSCAR|tail -1|tr -s [:space:]|sed 's/^[ ]*//g'|cut -d ' ' -f $j)
		elen=$(head -7 POSCAR|tail -1|tr -s [:space:]|sed 's/^[ ]*//g'|cut -d ' ' -f $j)
		if [ "$ele_old" == "$ele" ];then
			break
		fi
	done
	echo $atomnum
}

# main
while getopts "hmrc" opt; do
	case $opt in 
	h)
		help=true
	;;
	m)
		# check file
		check_program "phonopy"
		check_file "POSCAR"
		# check_file "KPOINTS"
		check_file "INCAR"
		check_file "POTCAR"
		check_file "thermal.conf"
		call_line
		# mkdir directions
		echo "Make direction QHA, QHA/DFPT, QHA/POSCAR_diff_scale"
		make_dir "QHA"
		make_dir "QHA/DFPT"
		make_dir "QHA/POSCAR_diff_scale"
		# create POSCAR with different volum
		echo "Create POSCAR from -$sn to $sn on POSCAR_diff_scale"
		cp POSCAR QHA/POSCAR_diff_scale/POSCAR-0
		cd QHA/POSCAR_diff_scale
		for i in $(seq 1 $sn); do
			cp POSCAR-0 POSCAR-$i
			new_scale=$(echo "scale=2; 1.00+$i*0.01" | bc)
			sed -i "2c$new_scale" POSCAR-$i
			cp POSCAR-0 POSCAR--$i
			new_scale=$(echo "scale=2; 1.00-$i*0.01" | bc)
			sed -i "2c$new_scale" POSCAR--$i
		done
		# prepare input files for calculation
		echo "Generate input files on DFPT, with SPOSCAR at dim $dim"
		cd ../DFPT
		for poscar in $(ls ../POSCAR_diff_scale | cat); do
			make_dir "$poscar"
			echo "Generate input files for $poscar"
			cp ../POSCAR_diff_scale/$poscar $poscar/POSCAR_unitcell
			cp ../../POTCAR ../../INCAR $poscar/ # ../../KPOINTS
			# use phonopy to create super cell
			cd $poscar
			phonopy -d --dim="$dim" -c POSCAR_unitcell >/dev/null
			mv SPOSCAR POSCAR
			cd ..
			done
		# make done
		echo "Input files were successfully generated on DFPT"
		echo "You can go into the DFPT direction and run tasks"
		call_line
	;;
	r)
		cd QHA/DFPT
		check_program "put"
		put rl
		qsub runvasploop.pbs
	;;
	c)
		check_program "phonopy"
		# mkdir direction
		call_line
		echo "Make direction QHA/Thermal_properties, QHA/QHA_results"
		make_dir "QHA/Thermal_properties"
		make_dir "QHA/QHA_results"
		cd QHA/DFPT
		# calculate thermal_properties for POSCARs at each volume
		echo "Start calculate thermal properties for each task"
		for poscar in $(ls|cat); do
			if [ -d $poscar ]; then
				echo "Calculate thermal properties for $poscar"
				cd $poscar
				cp ../../../thermal.conf ./
				phonopy --fc vasprun.xml >/dev/null
				phonopy -c POSCAR_unitcell -t thermal.conf >/dev/null
				suffix=$(echo $poscar | cut -d 'R' -f 2)
				mv thermal_properties.yaml ../../Thermal_properties/thermal_properties.yaml$suffix
				cd ..
			fi
		done
		# get EV data
		echo "Grep energy and volume data from outputs"
		#echo "#   cell volume   energy of cell other than phonon" >> e-v.dat
		#for i in $(seq $((-1*$sn)) $sn); do
			#cd POSCAR-$i
			#nunit=$(get_atomnum)
			#cd ..
			#volume=`grep volume     POSCAR-$i/vasprun.xml | tail -n 1 | awk -F '<|>' '{printf("%20.13f", $3)}'`
			#energy=`grep e_wo_entrp POSCAR-$i/vasprun.xml | tail -n 1 | awk -F '<|>' '{printf("%20.13f", $3)}'`
			#echo "$(echo "$volume/$nunit" | bc -l) $(echo "$energy/$nunit" | bc -l)" >> e-v.dat
		#done
		phonopy-vasp-efe --tmax=$Tmax $(eval echo "POSCAR-{-{$sn..1},{0..$sn}}/vasprun.xml")
		mv e-v.dat ../
		mv fe-v.dat ../
		# phonopy-qha
		echo "Run phonopy-qha, output files will store in QHA/QHA_results"
		cd ../QHA_results
		phonopy-qha --tmax=$Tmax --efe ../fe-v.dat ../e-v.dat $(eval echo "../Thermal_properties/thermal_properties.yaml-{-{$sn..1},{0..$sn}}")
		call_line
	;;
	esac
done

if [ "$help" = true ];then
	echo "To use this script to perfrom phonopy-qha calculation"
	echo "You should first prepare 4 VASP input files for DFPT, POSCAR should be a optimized unit cell, and a thermal.conf to perform phonopy"
	echo "Then, vi this script, modify dim and sn parameter, dim is the super POSCAR dimension, sn determine the number of volume points to pick"
	echo "Execute -m, this will create QHA direction and prepare VASP input files for POSCARs at different volume on QHA/DFPT"
	echo "Execute -r to run VASP calculations, you can also go into QHA/DFPT and run these tasks manually"
	echo "Execute -c, script will call phonopy to calculate thermal properties and perfrom phonopy-qha with these data"
	echo "The script needs to be run in the same directory as the prepared input file and the generated QHA folder"
fi
